### ISSUE TITLE
Switch for extended list of entities

### ISSUE THREAD

**Issue by maxwroc** [bieniu/ha-accuweather#5]
I think that most of the people don't use all of the entities which are being added by integration. And there is a lot of them actually.

For people who didn't configure recorder/history efficiently all of these will be logged by default - just spamming DB.

My proposal is to have the switch in the options which you can use to turn on the extended list of entities (should be off by default).

Yes, I know that you can hide not needed entities from any integration but it is a hassle and I think most people don't know about such option. :)

**Comment by maxwroc** [comment]
35 entities for weather integration is way to many IMO

**Comment by bieniu** [comment]
Only in exceptional cases HA Core reviewers allow you to hide entities through integration options because this duplicates the existing mechanism for disabling entities. If the user doesn't know the system he is using, this is his problem ;) This doesn't mean that the official version of the integration will not turn off more entities by default. Perhaps an option will be added to enable/disable all other entities except the one from the weather domain. A lot depends on the reviewers.

**Comment by bieniu** [comment]
> 35 entities for weather integration is way to many IMO

My DarkSky integration has 54 entities 😉

**Comment by maxwroc** [comment]
Wow that is crazy - I didn't know that. But anyway IMO that was not the right approach.

> If the user doesn't know the system he is using, this is his problem 😉 

And I don't agree with this statement. When system grows you end up with thousands of features/options/switches (it will be really hard to find/know all of them). HA seems to go now in direction to make the system more friendly to regular users (enforcing UI config and making yaml support optional) so we cannot think only about power users.

I think the correct approach is to think how majority of people would be using your feature. Besides after upgrading your integration all the disabled entities reappeared (these settings for disabling entities were lost). I'm not sure if this is by design or the reason was that it is a custom integration (and once this is integrated in the core it won't happen).

I saw your PR for HA core but I won't put such comment there as I don't want to block you (I know how hard is to push some changes there)

Anyway thanks again for this integration - I think that it is the best one currently (especially given that DarkSky will vanish soon!)

**Comment by bieniu** [comment]
Yes, you are right, HA as a whole should be simple and trouble-free for non-technical people.
The PR for HA Core contains only weather platform. The sensor platform will be added in the future. I prefer to divide the work into smaller parts. This makes it easier to review.
I'm open to your suggestions on how to solve the problem of entities quantity.  Especially since there will be more of them because I haven't added all the data to the sensor platform yet.
The matter would simplify the possibility of adding more data to the weather platform but this requires changes in the core. On the other hand, there is currently a discussion about removing the weather and air_quality platform and leave only the sensor.

**Comment by bieniu** [comment]
> Besides after upgrading your integration all the disabled entities reappeared
This shouldn't happen. Entities options are in the entity registry and integrations doesn't touch it. I will check this.
